### ISSUE TITLE
there is still messy display on welcome screen.

### ISSUE THREAD

**Issue by coolove** [DemonCloud/Aix-Vim#1]
for the version you uploaded today. win7 64bit.

as below:

![image](https://cloud.githubusercontent.com/assets/641877/7978779/e7a13642-0acb-11e5-984b-d4dd97f9d20c.png)

and could you please show me where  i can define this message? thanks.

**Comment by DemonCloud** [comment]
@coolove 

Hi~  I upload this GVim environment in Chinese Language Windows System

You can find

`_vimrc`  num: 61-62

``` VimL
set fencs=utf-8,GB18030,ucs-bom,default,latin1
set fileencodings=utf-8,chinese,latin-1
language messages zh_CN.utf-8
```

delete or comment them

**Comment by coolove** [comment]
thanks for your quick reply, actually delete the lines you mentioned is not working, but after i change the encoding from utf-8 to chinese, it can displayed properly as below:
![image](https://cloud.githubusercontent.com/assets/641877/7979931/10012836-0ad6-11e5-9315-3d0ea6ff1eed.png)
but it will cause another problem like this
![image](https://cloud.githubusercontent.com/assets/641877/7979947/4c88e410-0ad6-11e5-9b20-d70770c88e9f.png)

would you mind tell me where i can change the word "百合仙子". thanks.

**Comment by DemonCloud** [comment]
@coolove 

Nope , This text may added to the list when compiled.

You may find Vim source code project and modify the source code
recompiled and building it.

**Comment by coolove** [comment]
got it. just curious about it, i was gonna remove the word to avoid the messy content. looks like it won't gonna happen. thanks.

do you know why the Chinese encoding setting would  cause the error i posted. but the utf-8 setting is works fine?

**Comment by DemonCloud** [comment]
@coolove 

I just for define language for StatuLine , Terminal Line Menu Bar as Chinese 

It's because Window deal with encoding for Language form different way!
if you use the English Development Environment that you would not care about this..

sole: [Gvim Chinese encoding setting ](http://blog.csdn.net/rehung/article/details/1794293)

issue:
 [issue1](https://bugs.launchpad.net/ubuntu/+source/vim/+bug/617761)
 [issue2](http://www.dzhang.com/blog/2013/04/02/displaying-chinese-utf-8-characters-in-gvim-on-windows)
